/**
    Given a msg generated by hl7Split,
    join it back together.

    @param {Object} msg - The response object from hl7Split()
    @param {Object.String} msg.dField - The delimeter character
    @param {Object.Array} msg.segList - The array of arrays of segments of fields
	
    @return {String} return The joined hl7
*/


function hl7Join(msg) {
    // Put the transaction back together
    msg.segList.forEach(function (o, i, a) {
        a[i] = o.join(msg.dField);
    });

    return msg.segList.join("\r") + "\r";
}